"""Add role column to faculty

Revision ID: 540ee9653a22
Revises: a442757cc914
Create Date: 2026-08-13 17:54:21.017483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540ee9653a22'
down_revision: Union[str, None] = 'a442757cc914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('professor', 'teaching_assistant', name='faculty_role'), nullable=False, server_default='professor'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
