"""Add hours_per_week to subjects

Revision ID: 9666190ae8a8
Revises: 540ee9653a22
Create Date: 2026-08-14 00:28:25.111927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9666190ae8a8'
down_revision: Union[str, None] = '540ee9653a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours_per_week', sa.Integer(), server_default='4', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('hours_per_week')

    # ### end Alembic commands ###
