"""Add batch groups and subject types

Revision ID: ee56ca73837f
Revises: 9666190ae8a8
Create Date: 2026-09-17 23:17:32.514669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee56ca73837f'
down_revision: Union[str, None] = '9666190ae8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'name', name='uq_batch_group_name')
    )
    with op.batch_alter_table('batch_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_groups_id'), ['id'], unique=False)



    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('theory', 'lab', name='subject_type'), nullable=False, server_default='theory'))

    with op.batch_alter_table('timetable_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_batch_day_slot'), type_='unique')
        batch_op.create_unique_constraint('uq_batch_day_slot_group', ['batch_id', 'day', 'time_slot_id', 'group_id'])
        batch_op.create_index('uq_theory_entry', ['batch_id', 'day', 'time_slot_id'], unique=True, sqlite_where=sa.text('group_id IS NULL'), postgresql_where=sa.text('group_id IS NULL'))
        batch_op.create_foreign_key('fk_timetable_entries_group_id', 'batch_groups', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Safely remove concurrent lab entries before restoring uniqueness constraint
    op.execute("DELETE FROM timetable_entries WHERE id NOT IN (SELECT MIN(id) FROM timetable_entries GROUP BY batch_id, day, time_slot_id)")

    with op.batch_alter_table('timetable_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_timetable_entries_group_id', type_='foreignkey')
        batch_op.drop_index('uq_theory_entry', sqlite_where=sa.text('group_id IS NULL'), postgresql_where=sa.text('group_id IS NULL'))
        batch_op.drop_constraint('uq_batch_day_slot_group', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_batch_day_slot'), ['batch_id', 'day', 'time_slot_id'])
        batch_op.drop_column('group_id')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('type')

    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        sa.Enum('theory', 'lab', name='subject_type').drop(bind, checkfirst=True)


    with op.batch_alter_table('batch_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_groups_id'))

    op.drop_table('batch_groups')
    # ### end Alembic commands ###
